### ISSUE TITLE
Auth Tokens can expire (I think)

### ISSUE THREAD

**Issue by Skayo** [Ewpratten/devDNS#2]
If I'm not mistaken, your auth token will expire after a month.  
So if you manage to run you bot 24/7 for a month, it won't work anymore after that, because the token expired.  
The /users/auth-token endpoint returns a expire_time which you can just check against the current timestamp:

```python
if time.time() > token.expire_time:
    # Refresh the token
```

Not sure if the tokens **really** expire after a month tho as the WebApp still works after the token expired. 
Your decision...
Maybe dfox just forgot to remove it...

**Comment by Skayo** [comment]
What I've also noticed is that the cookies that stores the token in the WebApp expires in 2020.
Maybe that has something to do with the expire time?

**Comment by Skayo** [comment]
The bot that I'm currently working on just refreshes the token after it expired.
Doesn't harm. Isn't complicated. It's just a little "making sure it works".

**Comment by Ewpratten** [comment]
I have implemented this in my other bots, but since devDNS crashes every 30 mins, and is restarted by docker (don't ask), I think it's safe not to check for now
